import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import LoginPage from "./[locale]/(auth)/login/page";

const locale = "en";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={locale}>
      <body className="">
        <div className="flex flex-col md:flex-row items-center justify-center min-h-screen gap-8">
          <LoginPage params={{ lang: locale }} />
        </div>
        {children}
      </body>
    </html>
  );
}
