const mongoose = require('mongoose');

const CropPlanSchema = new mongoose.Schema({
    user: { // Links this crop plan to a specific farmer
        type: mongoose.Schema.ObjectId,
        ref: 'User',
        required: true
    },
    cropName: {
        type: String,
        required: [true, 'Please add a crop name'],
        trim: true,
        enum: ['Maize', 'Beans', 'Irish potatoes', 'Cassava', 'Tomatoes'] // Restrict to MVP crops
    },
    districtName: {
        type: String,
        required: [true, 'Please specify the district name'],
        trim: true
        // In a real app, you might want to validate this against a list of valid districts
    },
    actualAreaPlantedHa: {
        type: Number,
        required: [true, 'Please add the actual area planted in hectares'],
        min: [0.01, 'Area planted must be at least 0.01 hectares']
    },
    plantingDate: {
        type: Date,
        required: [true, 'Please add the planting date']
    },
    // These fields could store the estimates generated by the tracker, or be recalculated
    estimatedHarvestDate: {
        type: Date
    },
    estimatedYieldKgPerHa: {
        type: Number
    },
    estimatedTotalProductionKg: {
        type: Number
    },
    estimatedPricePerKgRwf: {
        type: Number
    },
    estimatedRevenueRwf: {
        type: Number
    },
    status: { // To track the lifecycle of the crop plan
        type: String,
        enum: ['Planned', 'Planted', 'Harvested', 'Completed', 'Cancelled'],
        default: 'Planted'
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

// Optional: Add a pre-save hook to automatically calculate estimates
// This ensures consistency but might be better handled in the controller
// to allow more dynamic interaction with analyticsService.
/*
CropPlanSchema.pre('save', async function(next) {
    if (this.isModified('actualAreaPlantedHa') || this.isModified('plantingDate') || this.isModified('districtName')) {
        // You'd need to access the analyticsService here, which is tricky in a Mongoose hook
        // Typically, this calculation happens in the controller before saving.
        // For now, we'll keep the estimation logic in the controller.
    }
    next();
});
*/

module.exports = mongoose.model('CropPlan', CropPlanSchema);