// src/config/districts.ts

export const RWANDA_DISTRICTS = [
  { label: 'Gasabo', value: 'Gasabo' },
  { label: 'Nyarugenge', value: 'Nyarugenge' },
  { label: 'Kicukiro', value: 'Kicukiro' },
  { label: 'Nyanza', value: 'Nyanza' },
  { label: 'Gisagara', value: 'Gisagara' },
  { label: 'Nyaruguru', value: 'Nyaruguru' },
  { label: 'Huye', value: 'Huye' },
  { label: 'Nyamagabe', value: 'Nyamagabe' },
  { label: 'Ruhango', value: 'Ruhango' },
  { label: 'Muhanga', value: 'Muhanga' },
  { label: 'Kamonyi', value: 'Kamonyi' },
  { label: 'Karongi', value: 'Karongi' },
  { label: 'Ngororero', value: 'Ngororero' },
  { label: 'Nyabihu', value: 'Nyabihu' },
  { label: 'Rubavu', value: 'Rubavu' },
  { label: 'Rusizi', value: 'Rusizi' },
  { label: 'Nyamasheke', value: 'Nyamasheke' },
  { label: 'Rutsiro', value: 'Rutsiro' },
  { label: 'Burera', value: 'Burera' },
  { label: 'Gakenke', value: 'Gakenke' },
  { label: 'Gicumbi', value: 'Gicumbi' },
  { label: 'Musanze', value: 'Musanze' },
  { label: 'Rulindo', value: 'Rulindo' },
  { label: 'Bugesera', value: 'Bugesera' },
  { label: 'Gatsibo', value: 'Gatsibo' },
  { label: 'Kayonza', value: 'Kayonza' },
  { label: 'Kirehe', value: 'Kirehe' },
  { label: 'Ngoma', value: 'Ngoma' },
  { label: 'Nyagatare', value: 'Nyagatare' },
  { label: 'Rwamagana', value: 'Rwamagana' },
];

export const RWANDA_PROVINCES = [
  { label: 'Kigali City', value: 'Kigali City' },
  { label: 'Southern Province', value: 'Southern Province' },
  { label: 'Western Province', value: 'Western Province' },
  { label: 'Northern Province', value: 'Northern Province' },
  { label: 'Eastern Province', value: 'Eastern Province' },
];